### DBPedia annotate request

GET http://model.dbpedia-spotlight.org/en/candidates?text={{text}}&confidence={{confidence}}
Accept: application/json

### SciGraph get by DOI

GET https://scigraph.springernature.com/api/redirect?doi={{doi}}
Accept: application/ld+json

### Unsilo get by DOI

GET https://api.unsilo.com/springer/related-content/2.7/document/v4/by-id/{{doi}}

### Dimensions DSL
POST https://app.dimensions.ai/api/auth.json HTTP/1.1
Content-Type: application/json
< ./dimensions-login.json

###
